#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
# git ls-files | \
#   ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-sql --exclude=node_modules
git ls-files | grep py$ | \
  ctags --tag-relative -L - -f"$dir/$$.pytags"

ctags -R --fields=+l --languages=python --python-kinds=-iv -f"$dir/$$.pytags" --append $(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))")

git ls-files | grep js$ | \
  ctags --tag-relative -L - -f"$dir/$$.jstags"
mv "$dir/$$.pytags" "$dir/pytags"
mv "$dir/$$.jstags" "$dir/jstags"

